export interface SimToolCall {
  name: string;
  server: string;
  params: Record<string, string | number | boolean | string[]>;
  result: string;
  live?: boolean;
}

export interface SimEvidence {
  type: string;
  value: string;
  threatScore?: number;
}

export interface SimStep {
  id: string;
  delay: number;
  agent: "Sentinel" | "Sherlock" | "Responder" | "Chronicler" | "Overseer" | "Archestra";
  action: string;
  details: string;
  toolCall?: SimToolCall;
  evidence?: SimEvidence;
  stage: "quarantine" | "triage" | "investigate" | "contain" | "report" | "oversee";
  severity?: string;
  cost: number;
}

export interface Scenario {
  id: string;
  title: string;
  subtitle: string;
  trigger: string;
  severity: string;
  mitre: string;
  steps: SimStep[];
}

export const scenarios: Scenario[] = [
  {
    id: "tor-credential",
    title: "Tor Exit Node Credential Attack",
    subtitle: "Coordinated authentication from Tor exit nodes targeting VPN gateway",
    trigger: "SIEM Alert #4721 — Auth anomaly from known Tor IP",
    severity: "P2 → P1",
    mitre: "T1078 Valid Accounts, T1133 External Remote Services",
    steps: [
      {
        id: "t0a",
        delay: 400,
        agent: "Archestra",
        action: "Dual LLM Security — Quarantine",
        details: "Incoming SIEM payload intercepted by Archestra Security Engine. Untrusted data isolated in quarantine sandbox. Sub-agent analyzing for prompt injection, data exfiltration vectors, and payload anomalies.",
        stage: "quarantine",
        cost: 0,
      },
      {
        id: "t0b",
        delay: 1200,
        agent: "Archestra",
        action: "Security Clearance — Passed",
        details: "Payload sanitized. No injection patterns detected. Tool policy check: Sentinel has access to incident-db (create, list, stats). Routing to Sentinel via Gemini 2.5 Flash (cost-optimized model selection).",
        stage: "quarantine",
        cost: 0,
      },
      {
        id: "t1",
        delay: 600,
        agent: "Sentinel",
        action: "Alert Received",
        details: "SIEM alert: Authentication from 198.51.100.23 flagged as Tor exit node. User: j.martinez@corp.com, Service: VPN Gateway.",
        stage: "triage",
        cost: 0,
      },
      {
        id: "t2",
        delay: 1800,
        agent: "Sentinel",
        action: "Classifying Severity",
        details: "Pattern match: tor_exit_node_auth → P2 (High). Confidence: 0.91. Prior incidents from this range: 2 in last 30d.",
        stage: "triage",
        cost: 0.001,
      },
      {
        id: "t3",
        delay: 1500,
        agent: "Sentinel",
        action: "Creating Incident",
        toolCall: {
          name: "create_incident",
          server: "incident-db",
          params: {
            title: "Tor Exit Node Auth — j.martinez",
            description: "Authentication attempts from Tor exit nodes targeting VPN gateway.",
            severity: "P2",
            type: "unauthorized_access",
            source: "siem-alert-4721",
            assigned_agent: "Sentinel",
          },
          result: "Created INC-2026-0042",
        },
        details: "",
        stage: "triage",
        cost: 0.001,
      },
      {
        id: "t4",
        delay: 1000,
        agent: "Sentinel",
        action: "Routing to Investigation",
        details: "Handing off to Sherlock for deep analysis. Triage completed in 3.2s.",
        stage: "triage",
        cost: 0,
      },
      {
        id: "t5",
        delay: 1400,
        agent: "Sherlock",
        action: "Starting Investigation",
        details: "Received INC-2026-0042. Beginning threat intel lookups on source IP and target service.",
        stage: "investigate",
        cost: 0,
      },
      {
        id: "t6",
        delay: 2000,
        agent: "Sherlock",
        action: "IP Threat Lookup",
        toolCall: {
          name: "check_ip",
          server: "threat-intel",
          params: { ip: "198.51.100.23" },
          result: "Threat Score: 92/100. Known Tor exit node. Last seen in brute-force campaigns targeting financial sector. ASN: AS9009 M247 Ltd. Country: Romania.",
        },
        evidence: { type: "ip", value: "198.51.100.23", threatScore: 92 },
        details: "",
        stage: "investigate",
        cost: 0.05,
      },
      {
        id: "t7",
        delay: 1800,
        agent: "Sherlock",
        action: "Target Service Analysis",
        toolCall: {
          name: "check_domain",
          server: "threat-intel",
          params: { domain: "vpn.corp.com" },
          result: "Internal VPN gateway. Critical asset (Tier 1). Last 24h: 3 anomalous auth attempts from distinct Tor exit nodes. Normal baseline: 0.",
        },
        details: "",
        stage: "investigate",
        cost: 0.05,
      },
      {
        id: "t8",
        delay: 2200,
        agent: "Sherlock",
        action: "Correlating Related Indicators",
        toolCall: {
          name: "bulk_check_ips",
          server: "threat-intel",
          params: { ips: ["198.51.100.23", "203.0.113.45", "203.0.113.78", "198.51.100.89"] },
          result: "4/4 confirmed malicious. All Tor exit nodes. Same /24 campaign cluster. First activity: 6h ago. Credential stuffing pattern detected.",
        },
        evidence: { type: "ip", value: "4 correlated Tor exit nodes identified", threatScore: 95 },
        details: "",
        stage: "investigate",
        cost: 0.05,
      },
      {
        id: "t9",
        delay: 1600,
        agent: "Sherlock",
        action: "Escalating to P1 — Coordinated Attack",
        details: "Evidence confirms coordinated credential stuffing via 4 Tor exit nodes targeting VPN gateway. Escalating P2 → P1.",
        severity: "P1",
        toolCall: {
          name: "update_incident",
          server: "incident-db",
          params: { id: "{{incident_id}}", severity: "P1", status: "investigating", details: "Escalated to P1 after coordinated Tor credential stuffing confirmed." },
          result: "Severity escalated to P1 (Critical)",
        },
        stage: "investigate",
        cost: 0.05,
      },
      {
        id: "t10",
        delay: 1200,
        agent: "Sherlock",
        action: "Evidence Attached",
        toolCall: {
          name: "add_evidence",
          server: "incident-db",
          params: {
            incident_id: "{{incident_id}}",
            type: "ip",
            content: "198.51.100.23, 203.0.113.45, 203.0.113.78, 198.51.100.89",
            source: "AbuseIPDB",
            collected_by: "Sherlock",
            threat_score: 95,
          },
          result: "4 evidence items attached to INC-2026-0042",
        },
        details: "",
        stage: "investigate",
        cost: 0.05,
      },
      {
        id: "t11",
        delay: 1000,
        agent: "Sherlock",
        action: "Investigation Complete",
        details: "Root cause: coordinated credential stuffing via Tor. 4 source IPs, 1 compromised session (j.martinez). Routing to Responder.",
        stage: "investigate",
        cost: 0,
      },
      {
        id: "t12",
        delay: 1400,
        agent: "Responder",
        action: "Planning Containment",
        details: "P1 incident requires Overseer approval. Proposed actions: block 4 IPs, revoke j.martinez sessions, enforce password reset.",
        stage: "contain",
        cost: 0,
      },
      {
        id: "t13",
        delay: 2000,
        agent: "Overseer",
        action: "Reviewing Containment Plan",
        details: "P1 containment: 4 IP blocks (72h TTL), 1 session revocation, 1 password reset. Risk: LOW — all defensive actions. APPROVED.",
        stage: "oversee",
        cost: 0.05,
      },
      {
        id: "t14",
        delay: 1800,
        agent: "Responder",
        action: "Blocking Source IPs",
        toolCall: {
          name: "block_ip",
          server: "security-playbook",
          params: {
            ips: ["198.51.100.23", "203.0.113.45", "203.0.113.78", "198.51.100.89"],
            reason: "Coordinated Tor credential stuffing campaign",
            duration_hours: 72,
            incident_id: "{{incident_id}}",
          },
          result: "4 IPs blocked at perimeter firewall. TTL: 72h. Rule ID: FW-2026-1847.",
        },
        details: "",
        stage: "contain",
        cost: 0.03,
      },
      {
        id: "t15",
        delay: 1500,
        agent: "Responder",
        action: "Revoking Compromised Session",
        toolCall: {
          name: "revoke_token",
          server: "security-playbook",
          params: {
            token_type: "session",
            identifier: "j.martinez@corp.com",
            reason: "Credential stuffing confirmed via Tor exit nodes",
            incident_id: "{{incident_id}}",
          },
          result: "All active sessions revoked. Password reset enforced. User notified via secondary channel.",
        },
        details: "",
        stage: "contain",
        cost: 0.03,
      },
      {
        id: "t16",
        delay: 1200,
        agent: "Responder",
        action: "Containment Complete",
        details: "4 IPs blocked, sessions revoked, password reset enforced. Routing to Chronicler for reporting.",
        stage: "contain",
        cost: 0.03,
      },
      {
        id: "t17",
        delay: 1800,
        agent: "Chronicler",
        action: "Generating Incident Report",
        details: "Compiling investigation timeline, evidence artifacts, and containment actions into structured report.",
        stage: "report",
        cost: 0.001,
      },
      {
        id: "t18",
        delay: 1500,
        agent: "Chronicler",
        action: "Compliance Check",
        details: "GDPR: No PII exfiltration confirmed. SOC 2: Response within SLA (4m 12s < 15m target). No regulatory notification required.",
        stage: "report",
        cost: 0.001,
      },
      {
        id: "t19",
        delay: 1400,
        agent: "Chronicler",
        action: "Incident Closed",
        toolCall: {
          name: "update_incident",
          server: "incident-db",
          params: {
            id: "{{incident_id}}",
            status: "closed",
            details: "Coordinated credential attack contained. Sessions revoked and IPs blocked.",
            cost_usd: 0.38,
          },
          result: "INC-2026-0042 closed. MTTR: 4m 12s. Cost: $0.38.",
        },
        details: "",
        stage: "report",
        cost: 0.001,
      },
    ],
  },
  {
    id: "supply-chain",
    title: "Supply Chain Malware in CI/CD",
    subtitle: "Malicious npm package detected in build pipeline with known CVE",
    trigger: "CI Pipeline Alert — Suspicious hash in dependency tree",
    severity: "P2",
    mitre: "T1195.002 Supply Chain Compromise",
    steps: [
      {
        id: "s0a",
        delay: 400,
        agent: "Archestra",
        action: "Dual LLM Security — Quarantine",
        details: "CI pipeline payload intercepted. Archestra Security Engine isolating untrusted build artifact metadata. Scanning for embedded injection vectors in package manifest.",
        stage: "quarantine",
        cost: 0,
      },
      {
        id: "s0b",
        delay: 1100,
        agent: "Archestra",
        action: "Security Clearance — Passed",
        details: "No injection in payload. Tool policy verified: Sentinel → incident-db (create). Dynamic model routing: Gemini 2.5 Flash selected for triage (cost tier: $0). Releasing to agent pipeline.",
        stage: "quarantine",
        cost: 0,
      },
      {
        id: "s1",
        delay: 600,
        agent: "Sentinel",
        action: "Alert Received",
        details: "CI pipeline alert: Package colors-js@1.4.1 resolved to unexpected hash. Build environment: staging-build-07.",
        stage: "triage",
        cost: 0,
      },
      {
        id: "s2",
        delay: 1600,
        agent: "Sentinel",
        action: "Classifying Severity",
        details: "Pattern match: suspicious_package_hash → P2 (High). Supply chain indicators present. Confidence: 0.88.",
        stage: "triage",
        cost: 0.001,
      },
      {
        id: "s3",
        delay: 1400,
        agent: "Sentinel",
        action: "Creating Incident",
        toolCall: {
          name: "create_incident",
          server: "incident-db",
          params: {
            title: "Suspicious npm package hash — colors-js",
            description: "CI pipeline flagged malicious hash in dependency tree (colors-js@1.4.1).",
            severity: "P2",
            type: "malware",
            source: "ci-pipeline-alert",
            assigned_agent: "Sentinel",
          },
          result: "Created INC-2026-0043",
        },
        details: "",
        stage: "triage",
        cost: 0.001,
      },
      {
        id: "s4",
        delay: 1000,
        agent: "Sentinel",
        action: "Routing to Investigation",
        details: "Supply chain threat detected. Routing to Sherlock for hash analysis and CVE correlation.",
        stage: "triage",
        cost: 0,
      },
      {
        id: "s5",
        delay: 1500,
        agent: "Sherlock",
        action: "Hash Analysis",
        toolCall: {
          name: "check_hash",
          server: "threat-intel",
          params: { hash: "e3b0c44298fc1c14...a495991b7852b855", type: "sha256" },
          result: "MALICIOUS. VirusTotal: 47/72 detections. Family: Trojan.NPM.Colorstorm. First seen: 2026-02-07. Behavior: data exfiltration via DNS, environment variable harvesting.",
        },
        evidence: { type: "hash", value: "e3b0c44298fc1c14...a495991b7852b855", threatScore: 98 },
        details: "",
        stage: "investigate",
        cost: 0.05,
      },
      {
        id: "s6",
        delay: 1800,
        agent: "Sherlock",
        action: "CVE Lookup",
        toolCall: {
          name: "check_cve",
          server: "threat-intel",
          params: { cve_id: "CVE-2026-0891" },
          result: "CVE-2026-0891 (CVSS 9.8). Prototype pollution leading to arbitrary code execution. Published 2026-02-06. Patched in 1.4.2.",
        },
        evidence: { type: "hash", value: "CVE-2026-0891 (CVSS 9.8)", threatScore: 98 },
        details: "",
        stage: "investigate",
        cost: 0.05,
      },
      {
        id: "s7",
        delay: 1500,
        agent: "Sherlock",
        action: "Blast Radius Assessment",
        details: "Package installed in 3 services: auth-api, user-service, payment-gateway. Build artifacts deployed to staging only. Production not affected.",
        stage: "investigate",
        cost: 0.05,
      },
      {
        id: "s8",
        delay: 1200,
        agent: "Sherlock",
        action: "Investigation Complete",
        details: "Confirmed malicious package with known CVE. Staging-only blast radius. 3 services affected. Routing to Responder for containment.",
        stage: "investigate",
        cost: 0,
      },
      {
        id: "s9",
        delay: 1400,
        agent: "Responder",
        action: "Isolating Build Environment",
        toolCall: {
          name: "isolate_host",
          server: "security-playbook",
          params: {
            host: "staging-build-07",
            reason: "Malicious dependency detected in CI pipeline",
            preserve_evidence: true,
            incident_id: "{{incident_id}}",
          },
          result: "Build server isolated. Network access revoked. Running processes snapshot captured.",
        },
        details: "",
        stage: "contain",
        cost: 0.03,
      },
      {
        id: "s10",
        delay: 1800,
        agent: "Responder",
        action: "Executing Remediation Playbook",
        toolCall: {
          name: "execute_playbook",
          server: "security-playbook",
          params: {
            playbook: "supply_chain_remediation",
            target: "colors-js@1.4.1",
            incident_id: "{{incident_id}}",
          },
          result: "Playbook executed: package-lock purged, dependency pinned to 1.4.2, npm cache cleared across all build nodes, staging deployments rolled back.",
        },
        details: "",
        stage: "contain",
        cost: 0.03,
      },
      {
        id: "s11",
        delay: 1500,
        agent: "Responder",
        action: "Revoking CI Credentials",
        toolCall: {
          name: "revoke_token",
          server: "security-playbook",
          params: {
            token_type: "service_account",
            identifier: "ci-service-account",
            reason: "Supply chain compromise containment",
            incident_id: "{{incident_id}}",
          },
          result: "CI service account tokens rotated. AWS keys regenerated. NPM publish token revoked and reissued.",
        },
        details: "",
        stage: "contain",
        cost: 0.03,
      },
      {
        id: "s12",
        delay: 1200,
        agent: "Responder",
        action: "Containment Complete",
        details: "Build env isolated, malicious package removed, credentials rotated, staging rolled back. No production impact.",
        stage: "contain",
        cost: 0,
      },
      {
        id: "s13",
        delay: 1800,
        agent: "Chronicler",
        action: "Generating Report",
        details: "Documenting supply chain attack vector, affected services, and remediation steps. Preparing CVE advisory for engineering team.",
        stage: "report",
        cost: 0.001,
      },
      {
        id: "s14",
        delay: 1400,
        agent: "Chronicler",
        action: "Incident Closed",
        toolCall: {
          name: "update_incident",
          server: "incident-db",
          params: {
            id: "{{incident_id}}",
            status: "closed",
            details: "Malicious npm package contained, credentials rotated, staging rebuilt.",
            cost_usd: 0.27,
          },
          result: "INC-2026-0043 closed. MTTR: 3m 48s. Cost: $0.27.",
        },
        details: "",
        stage: "report",
        cost: 0.001,
      },
    ],
  },
  {
    id: "dns-exfil",
    title: "DNS Tunnel Data Exfiltration",
    subtitle: "Anomalous DNS query volume from internal workstation indicates data exfiltration",
    trigger: "Network Monitor — DNS query volume 40x baseline from single host",
    severity: "P2 → P1",
    mitre: "T1048.003 Exfiltration Over DNS, T1071.004 Application Layer Protocol",
    steps: [
      {
        id: "d0a",
        delay: 400,
        agent: "Archestra",
        action: "Dual LLM Security — Quarantine",
        details: "Network monitor payload intercepted. Archestra Security Engine quarantining DNS query samples. Sub-agent checking for embedded exfiltration payloads within the alert metadata itself.",
        stage: "quarantine",
        cost: 0,
      },
      {
        id: "d0b",
        delay: 1300,
        agent: "Archestra",
        action: "Security Clearance — Flagged",
        details: "Alert payload contains raw DNS query strings with base64-encoded subdomains. Data compressed and isolated — agents will receive sanitized summary only. Tool policy: Sherlock → threat-intel (check_ip, check_domain). Model: Gemini 2.5 Pro (forensics tier).",
        stage: "quarantine",
        cost: 0,
      },
      {
        id: "d1",
        delay: 600,
        agent: "Sentinel",
        action: "Alert Received",
        details: "Network anomaly: Workstation WS-FIN-042 generating 12,400 DNS queries/hour (baseline: 310). Query pattern: long subdomain strings to ext-analytics.xyz.",
        stage: "triage",
        cost: 0,
      },
      {
        id: "d2",
        delay: 1700,
        agent: "Sentinel",
        action: "Classifying Severity",
        details: "Pattern match: dns_tunnel_exfil → P2 (High). DGA-like subdomain patterns detected. Data exfiltration probability: 0.94.",
        stage: "triage",
        cost: 0.001,
      },
      {
        id: "d3",
        delay: 1400,
        agent: "Sentinel",
        action: "Creating Incident",
        toolCall: {
          name: "create_incident",
          server: "incident-db",
          params: {
            title: "DNS Tunnel Exfiltration — WS-FIN-042",
            description: "Anomalous DNS query volume with base64 subdomains indicates possible data exfiltration.",
            severity: "P2",
            type: "data_breach",
            source: "network-monitor",
            assigned_agent: "Sentinel",
          },
          result: "Created INC-2026-0044",
        },
        details: "",
        stage: "triage",
        cost: 0.001,
      },
      {
        id: "d4",
        delay: 1500,
        agent: "Sherlock",
        action: "Domain Analysis",
        toolCall: {
          name: "check_domain",
          server: "threat-intel",
          params: { domain: "ext-analytics.xyz" },
          result: "Threat Score: 97/100. Registered 48h ago via privacy proxy. Nameservers hosted on bulletproof infrastructure (AS200019). Known DNS tunneling C2 pattern. TXT record payload encoding detected.",
        },
        evidence: { type: "domain", value: "ext-analytics.xyz", threatScore: 97 },
        details: "",
        stage: "investigate",
        cost: 0.05,
      },
      {
        id: "d5",
        delay: 1800,
        agent: "Sherlock",
        action: "C2 Server Identification",
        toolCall: {
          name: "check_ip",
          server: "threat-intel",
          params: { ip: "45.95.147.12" },
          result: "Threat Score: 89/100. Resolves for ext-analytics.xyz. Located: Moldova. Hosting provider flagged for abuse. 6 other DNS tunnel domains on same IP in last 7d.",
        },
        evidence: { type: "ip", value: "45.95.147.12 (C2 server)", threatScore: 89 },
        details: "",
        stage: "investigate",
        cost: 0.05,
      },
      {
        id: "d6",
        delay: 1600,
        agent: "Sherlock",
        action: "Data Volume Estimation",
        details: "DNS query analysis: ~2.3MB encoded data exfiltrated over 4 hours. Subdomain encoding pattern consistent with iodine/dnscat2 tunnel. Source: WS-FIN-042 (Finance dept, user: a.chen@corp.com).",
        evidence: { type: "log", value: "~2.3MB exfiltrated via DNS over 4h", threatScore: 95 },
        stage: "investigate",
        cost: 0.05,
      },
      {
        id: "d7",
        delay: 1500,
        agent: "Sherlock",
        action: "Escalating to P1 — Active Data Breach",
        details: "Active data exfiltration from finance workstation confirmed. Escalating P2 → P1. Potential PII/financial data compromise.",
        severity: "P1",
        toolCall: {
          name: "update_incident",
          server: "incident-db",
          params: { id: "{{incident_id}}", severity: "P1", status: "investigating", details: "Confirmed DNS exfiltration. Escalated to P1." },
          result: "Severity escalated to P1 (Critical)",
        },
        stage: "investigate",
        cost: 0.05,
      },
      {
        id: "d8",
        delay: 1000,
        agent: "Sherlock",
        action: "Investigation Complete",
        details: "DNS tunnel exfiltration confirmed. C2: ext-analytics.xyz (45.95.147.12). ~2.3MB exfiltrated. Finance workstation compromised. Routing to Responder.",
        stage: "investigate",
        cost: 0,
      },
      {
        id: "d9",
        delay: 2000,
        agent: "Overseer",
        action: "P1 Containment Approval",
        details: "Active exfiltration — immediate containment required. Actions: isolate workstation, block C2 domain, quarantine user account, preserve forensic evidence. APPROVED — priority override.",
        stage: "oversee",
        cost: 0.05,
      },
      {
        id: "d10",
        delay: 1600,
        agent: "Responder",
        action: "Isolating Workstation",
        toolCall: {
          name: "isolate_host",
          server: "security-playbook",
          params: {
            host: "WS-FIN-042",
            reason: "Active DNS exfiltration detected",
            preserve_evidence: true,
            incident_id: "{{incident_id}}",
          },
          result: "Workstation isolated from network. DNS traffic blocked. Memory dump initiated for forensic analysis.",
        },
        details: "",
        stage: "contain",
        cost: 0.03,
      },
      {
        id: "d11",
        delay: 1500,
        agent: "Responder",
        action: "Blocking C2 Infrastructure",
        toolCall: {
          name: "block_ip",
          server: "security-playbook",
          params: {
            ip: "45.95.147.12",
            reason: "DNS tunneling C2 infrastructure",
            duration_hours: 0,
            incident_id: "{{incident_id}}",
          },
          result: "C2 IP and domain blocked at DNS resolver and firewall. Sinkhole configured.",
        },
        details: "",
        stage: "contain",
        cost: 0.03,
      },
      {
        id: "d12",
        delay: 1500,
        agent: "Responder",
        action: "Quarantining User Account",
        toolCall: {
          name: "revoke_token",
          server: "security-playbook",
          params: {
            token_type: "session",
            identifier: "a.chen@corp.com",
            reason: "Account associated with DNS exfiltration host",
            incident_id: "{{incident_id}}",
          },
          result: "All access revoked for a.chen. Account flagged for security review. Manager notified.",
        },
        details: "",
        stage: "contain",
        cost: 0.03,
      },
      {
        id: "d13",
        delay: 1200,
        agent: "Responder",
        action: "Containment Complete",
        details: "Host isolated, C2 blocked, user quarantined, forensic evidence preserved. Exfiltration stopped. Routing to Chronicler.",
        stage: "contain",
        cost: 0,
      },
      {
        id: "d14",
        delay: 1800,
        agent: "Chronicler",
        action: "Compliance Assessment",
        details: "GDPR: Potential PII breach — finance workstation may contain personal data. 72h notification clock started. DPO notified. SOC 2: Incident response within SLA.",
        stage: "report",
        cost: 0.001,
      },
      {
        id: "d15",
        delay: 1500,
        agent: "Chronicler",
        action: "Incident Closed — Pending Forensics",
        toolCall: {
          name: "update_incident",
          server: "incident-db",
          params: {
            id: "{{incident_id}}",
            status: "closed",
            details: "DNS exfiltration contained; forensic analysis ongoing. GDPR notification pending.",
            cost_usd: 0.41,
          },
          result: "INC-2026-0044 closed. MTTR: 3m 54s. Cost: $0.41. Note: GDPR notification pending forensic results.",
        },
        details: "",
        stage: "report",
        cost: 0.001,
      },
    ],
  },
];
